# Generated by Django 5.2.6 on 2025-11-23 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GatheringMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("leader", "모임장"), ("participant", "참여자")],
                        default="participant",
                        max_length=20,
                        verbose_name="역할",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "대기중"), ("approved", "승인됨"), ("rejected", "거절됨")],
                        default="pending",
                        max_length=20,
                        verbose_name="참여 상태",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="참여일")),
                ("is_active", models.BooleanField(default=True, verbose_name="활동 여부")),
            ],
            options={
                "verbose_name": "모임 멤버",
                "verbose_name_plural": "모임 멤버",
                "db_table": "gathering_members",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="카테고리명")),
                ("description", models.TextField(blank=True, null=True, verbose_name="카테고리 설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="gatherings.category",
                        verbose_name="부모 카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "카테고리",
                "verbose_name_plural": "카테고리",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Gathering",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("study", "스터디"), ("project", "프로젝트")], max_length=20, verbose_name="모임 유형"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("description", models.TextField(verbose_name="상세 설명")),
                ("max_members", models.IntegerField(verbose_name="모집 인원")),
                ("current_members", models.IntegerField(default=1, verbose_name="현재 참여 인원")),
                ("recruitment_end", models.DateField(verbose_name="모집 마감일")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="종료일")),
                ("meeting_schedule", models.CharField(blank=True, max_length=255, null=True, verbose_name="모임 일정")),
                (
                    "study_type",
                    models.CharField(
                        choices=[("online", "온라인"), ("offline", "오프라인"), ("mixed", "혼합")],
                        max_length=20,
                        verbose_name="진행 방식",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True, verbose_name="모임 장소")),
                (
                    "target_level",
                    models.CharField(
                        choices=[
                            ("beginner", "초급자"),
                            ("intermediate", "중급자"),
                            ("advanced", "고급자"),
                            ("all", "누구나"),
                        ],
                        max_length=20,
                        verbose_name="대상 수준",
                    ),
                ),
                ("has_cost", models.BooleanField(default=False, verbose_name="참가비 여부")),
                (
                    "cost_description",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="참가비 설명"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recruiting", "모집중"),
                            ("recruitment_complete", "모집완료"),
                            ("in_progress", "진행중"),
                            ("finished", "종료"),
                        ],
                        default="recruiting",
                        max_length=30,
                        verbose_name="모집 상태",
                    ),
                ),
                ("required_skills", models.TextField(blank=True, null=True, verbose_name="필요 기술 스택")),
                ("project_goal", models.TextField(blank=True, null=True, verbose_name="프로젝트 목표")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gatherings",
                        to="gatherings.category",
                        verbose_name="카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "모임",
                "verbose_name_plural": "모임",
                "db_table": "gatherings",
                "ordering": ["-created_at"],
            },
        ),
    ]
