# Generated by Django 5.2.6 on 2025-11-23 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gatherings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gathering",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_gatherings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AddField(
            model_name="gatheringmember",
            name="gathering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="gatherings.gathering",
                verbose_name="모임",
            ),
        ),
        migrations.AddField(
            model_name="gatheringmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gathering_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["parent"], name="idx_category_parent"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["is_active"], name="idx_category_active"),
        ),
        migrations.AddIndex(
            model_name="gathering",
            index=models.Index(fields=["user"], name="idx_gathering_user"),
        ),
        migrations.AddIndex(
            model_name="gathering",
            index=models.Index(fields=["category"], name="idx_gathering_category"),
        ),
        migrations.AddIndex(
            model_name="gathering",
            index=models.Index(fields=["type"], name="idx_gathering_type"),
        ),
        migrations.AddIndex(
            model_name="gathering",
            index=models.Index(fields=["status"], name="idx_gathering_status"),
        ),
        migrations.AddIndex(
            model_name="gathering",
            index=models.Index(fields=["recruitment_end"], name="idx_gathering_recruit_end"),
        ),
        migrations.AddIndex(
            model_name="gathering",
            index=models.Index(fields=["start_date"], name="idx_gathering_start_date"),
        ),
        migrations.AddIndex(
            model_name="gathering",
            index=models.Index(fields=["-created_at"], name="idx_gathering_created"),
        ),
        migrations.AddIndex(
            model_name="gatheringmember",
            index=models.Index(fields=["user"], name="idx_member_user"),
        ),
        migrations.AddIndex(
            model_name="gatheringmember",
            index=models.Index(fields=["gathering"], name="idx_member_gathering"),
        ),
        migrations.AddIndex(
            model_name="gatheringmember",
            index=models.Index(fields=["status"], name="idx_member_status"),
        ),
        migrations.AddIndex(
            model_name="gatheringmember",
            index=models.Index(fields=["is_active"], name="idx_member_active"),
        ),
        migrations.AlterUniqueTogether(
            name="gatheringmember",
            unique_together={("user", "gathering")},
        ),
    ]
