# Generated by Django 5.2.6 on 2025-11-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="답변 내용")),
            ],
            options={
                "verbose_name": "답변",
                "verbose_name_plural": "답변",
                "db_table": "answers",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="질문 제목")),
                ("content", models.TextField(verbose_name="질문 내용")),
                ("view_count", models.IntegerField(default=0, verbose_name="조회수")),
                ("is_solved", models.BooleanField(default=False, verbose_name="답변 여부")),
            ],
            options={
                "verbose_name": "질문",
                "verbose_name_plural": "질문",
                "db_table": "questions",
                "ordering": ["-created_at"],
            },
        ),
    ]
