# Generated by Django 5.2.6 on 2025-11-21 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gatherings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="질문 제목")),
                ("content", models.TextField(verbose_name="질문 내용")),
                ("view_count", models.IntegerField(default=0, verbose_name="조회수")),
                ("is_solved", models.BooleanField(default=False, verbose_name="답변 여부")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="gatherings.category",
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "질문",
                "verbose_name_plural": "질문",
                "db_table": "questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="답변 내용")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="답변 작성자",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="communitys.question",
                        verbose_name="질문",
                    ),
                ),
            ],
            options={
                "verbose_name": "답변",
                "verbose_name_plural": "답변",
                "db_table": "answers",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["user"], name="idx_question_user"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["category"], name="idx_question_category"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["is_solved"], name="idx_question_solved"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["-created_at"], name="idx_question_created"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["-view_count"], name="idx_question_views"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["question", "created_at"], name="idx_answer_question_created"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["user"], name="idx_answer_user"),
        ),
    ]
