# Generated by Django 5.2.6 on 2025-11-23 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communitys", "0001_initial"),
        ("gatherings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="답변 작성자",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="gatherings.category",
                verbose_name="카테고리",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="communitys.question",
                verbose_name="질문",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["user"], name="idx_question_user"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["category"], name="idx_question_category"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["is_solved"], name="idx_question_solved"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["-created_at"], name="idx_question_created"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["-view_count"], name="idx_question_views"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["question", "created_at"], name="idx_answer_question_created"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["user"], name="idx_answer_user"),
        ),
    ]
