# Generated by Django 5.2.6 on 2025-11-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=20, verbose_name="사용자명")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="이메일")),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "관리자"), ("user", "일반 사용자")],
                        default="user",
                        max_length=10,
                        verbose_name="역할",
                    ),
                ),
                (
                    "joined_type",
                    models.CharField(
                        choices=[("kakao", "카카오"), ("google", "구글"), ("naver", "네이버"), ("normal", "일반")],
                        max_length=20,
                        verbose_name="가입유형",
                    ),
                ),
                ("profile", models.TextField(blank=True, null=True, verbose_name="프로필")),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile_images/", verbose_name="프로필 이미지"),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("elementary_school", "초등학생"),
                            ("middle_school", "중학생"),
                            ("high_school", "고등학생"),
                            ("university_student", "대학생"),
                            ("graduate_student", "대학원생"),
                            ("office_worker", "직장인"),
                            ("job_seeker", "취업준비생"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="교육수준",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True, verbose_name="지역")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="탈퇴 여부")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="탈퇴 일시")),
                (
                    "deletion_scheduled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완전 삭제 예정 일시"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 상태")),
                ("is_staff", models.BooleanField(default=False, verbose_name="스태프 권한")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자들",
                "db_table": "users",
                "indexes": [
                    models.Index(fields=["is_deleted"], name="idx_user_is_deleted"),
                    models.Index(fields=["joined_type"], name="idx_user_joined_type"),
                    models.Index(fields=["created_at"], name="idx_user_created_at"),
                    models.Index(fields=["email", "is_deleted"], name="idx_user_email_deleted"),
                ],
            },
        ),
    ]
