# Generated by Django 5.2.6 on 2025-10-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_user_deleted_at_user_deletion_scheduled_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="탈퇴 일시"),
        ),
        migrations.AlterField(
            model_name="user",
            name="deletion_scheduled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="완전 삭제 예정 일시"),
        ),
        migrations.AlterField(
            model_name="user",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("elementary_school", "초등학생"),
                    ("middle_school", "중학생"),
                    ("high_school", "고등학생"),
                    ("university_student", "대학생"),
                    ("graduate_student", "대학원생"),
                    ("office_worker", "직장인"),
                    ("job_seeker", "취업준비생"),
                    ("other", "기타"),
                ],
                max_length=20,
                null=True,
                verbose_name="교육수준",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(default=0, verbose_name="로그인 실패 횟수"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성 상태"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="탈퇴 여부"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="스태프 권한"),
        ),
        migrations.AlterField(
            model_name="user",
            name="joined_type",
            field=models.CharField(
                choices=[("kakao", "카카오"), ("google", "구글"), ("naver", "네이버"), ("normal", "일반")],
                max_length=20,
                verbose_name="가입유형",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_failed_login",
            field=models.DateTimeField(blank=True, null=True, verbose_name="마지막 로그인 실패 시각"),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="지역"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.TextField(blank=True, null=True, verbose_name="프로필"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/", verbose_name="프로필 이미지"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "관리자"), ("user", "일반 사용자")],
                default="user",
                max_length=10,
                verbose_name="역할",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20, verbose_name="사용자명"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_deleted"], name="idx_user_is_deleted"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["joined_type"], name="idx_user_joined_type"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="idx_user_created_at"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email", "is_deleted"], name="idx_user_email_deleted"),
        ),
    ]
