# Generated by Django 5.2.6 on 2025-11-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="failed_login_attempts",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_failed_login",
        ),
    ]
