"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env_path = BASE_DIR / ".envs" / f".{os.getenv('DJANGO_ENV', 'dev')}.env"
load_dotenv(dotenv_path=env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if SECRET_KEY is None:
    raise ValueError("DJANGO_SECRET_KEY environment variable is not set.")


DEBUG = False

ALLOWED_HOSTS = []

# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

PACKAGE = [
    # REST API
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "drf_spectacular",
    # Authentication
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.naver",
    "allauth.socialaccount.providers.kakao",
    # Django Packages
    "corsheaders",
    "channels",
    "django_extensions",
]

LOCAL_APPS = [
    "apps.common",
    "apps.users",
    "apps.communitys",
    "apps.chat",
    "apps.gatherings",
]

INSTALLED_APPS = DJANGO_APPS + PACKAGE + LOCAL_APPS


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "apps" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# REST Framework 설정
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.users.authentication.CustomCookieAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# Spectacular 설정 (API 문서화)
SPECTACULAR_SETTINGS = {
    "TITLE": "GatherGrow API",
    "DESCRIPTION": "GatherGrow 프로젝트 API 문서",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Channels (WebSocket) 설정
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")],
        },
    },
}


# Social Auth Configuration - 환경 변수로부터 설정
SOCIAL_AUTH_CONFIG = {
    "GOOGLE": {
        "CLIENT_ID": os.environ.get("SOCIAL_AUTH_GOOGLE_CLIENT_ID"),
        "SECRET_KEY": os.environ.get("SOCIAL_AUTH_GOOGLE_SECRET_KEY"),
        "REDIRECT_URI": os.environ.get("SOCIAL_AUTH_GOOGLE_REDIRECT_URI"),
    },
    "NAVER": {
        "CLIENT_ID": os.environ.get("SOCIAL_AUTH_NAVER_CLIENT_ID"),
        "SECRET_KEY": os.environ.get("SOCIAL_AUTH_NAVER_SECRET_KEY"),
        "REDIRECT_URI": os.environ.get("SOCIAL_AUTH_NAVER_REDIRECT_URI"),
    },
    "KAKAO": {
        "CLIENT_ID": os.environ.get("SOCIAL_AUTH_KAKAO_CLIENT_ID"),
        "SECRET_KEY": os.environ.get("SOCIAL_AUTH_KAKAO_SECRET_KEY"),
        "REDIRECT_URI": os.environ.get("SOCIAL_AUTH_KAKAO_REDIRECT_URI"),
    },
}

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": SOCIAL_AUTH_CONFIG["GOOGLE"]["CLIENT_ID"],
            "secret": SOCIAL_AUTH_CONFIG["GOOGLE"]["SECRET_KEY"],
            "key": SOCIAL_AUTH_CONFIG["GOOGLE"]["CLIENT_ID"],
            "redirect_uri": SOCIAL_AUTH_CONFIG["GOOGLE"]["REDIRECT_URI"],
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "OAUTH_PKCE_ENABLED": True,
    },
    "naver": {
        "APP": {
            "client_id": SOCIAL_AUTH_CONFIG["NAVER"]["CLIENT_ID"],
            "secret": SOCIAL_AUTH_CONFIG["NAVER"]["SECRET_KEY"],
            "key": SOCIAL_AUTH_CONFIG["NAVER"]["CLIENT_ID"],
            "redirect_uri": SOCIAL_AUTH_CONFIG["NAVER"]["REDIRECT_URI"],
        }
    },
    "kakao": {
        "ADAPTER": "apps.users.adapters.kakao_adapter.CustomKakaoOAuth2Adapter",
        "APP": {
            "client_id": SOCIAL_AUTH_CONFIG["KAKAO"]["CLIENT_ID"],
            "secret": SOCIAL_AUTH_CONFIG["KAKAO"]["SECRET_KEY"],
            "key": SOCIAL_AUTH_CONFIG["KAKAO"]["CLIENT_ID"],
            "redirect_uri": SOCIAL_AUTH_CONFIG["KAKAO"]["REDIRECT_URI"],
        },
        "SCOPE": [
            "profile_nickname",
            "account_email",
        ],
    },
}

AUTH_USER_MODEL = "users.User"

# Simple JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# allauth와 연동 설정
SITE_ID = 1

# allauth 설정 (최신 방식)
REST_USE_JWT = True
JWT_AUTH_COOKIE = "access_token"
JWT_AUTH_REFRESH_COOKIE = "refresh_token"
JWT_AUTH_COOKIE_SECURE = False
JWT_AUTH_COOKIE_HTTPONLY = True
JWT_AUTH_COOKIE_SAMESITE = "Lax"

ACCOUNT_LOGIN_METHODS = ["email"]
ACCOUNT_AUTHENTICATION_METHODS = "email"

# 커스텀 소셜 계정 어댑터 설정 (필요시 추가)

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "access_token",
    "JWT_AUTH_REFRESH_COOKIE": "refresh_token",
    "JWT_AUTH_COOKIE_SECURE": False,
    # 토큰을 본문에 포함시키지 않음
    "JWT_AUTH_COOKIE_HTTPONLY": True,
    "JWT_AUTH_COOKIE_SAMESITE": "Lax",
}


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.naver.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
