# Generated by Django 5.2.6 on 2025-11-23 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField(blank=True, null=True, verbose_name="메시지 내용")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="지원 형식: JPG, JPEG, PNG, GIF, WebP (최대 5MB)",
                        null=True,
                        upload_to="chat_images/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"],
                                message="지원하지 않는 이미지 형식입니다. jpg, jpeg, png, gif, webp 형식만 업로드 가능합니다.",
                            )
                        ],
                        verbose_name="이미지",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 메시지",
                "verbose_name_plural": "채팅 메시지",
                "db_table": "chat_messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
