# Generated by Django 5.2.6 on 2025-11-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat_images/%Y/%m/%d/", verbose_name="이미지"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="메시지 내용"),
        ),
    ]
