# Generated by Django 5.2.6 on 2025-11-13 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_image_alter_chatmessage_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="지원 형식: JPG, JPEG, PNG, GIF, WebP (최대 5MB)",
                null=True,
                upload_to="chat_images/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"],
                        message="지원하지 않는 이미지 형식입니다. jpg, jpeg, png, gif, webp 형식만 업로드 가능합니다.",
                    )
                ],
                verbose_name="이미지",
            ),
        ),
    ]
